CREATE TABLE Client (
                        Client_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                        Admin_Contact VARCHAR (100),
                        Company_Name VARCHAR (100),
                        Client_Status VARCHAR (100),
                        Client_DateCreated DATE,
                        Client_DateUpdated DATE
)
CREATE TABLE Manager (
                         Manager_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                         Client INT,
                         Manager_Firstname VARCHAR (100),
                         Manager_Lastname VARCHAR (100),
                         Manager_Email VARCHAR (100),
                         Manager_Phonenumber VARCHAR (100),
                         Manager_Status VARCHAR (100),
                         Manager_DateCreated DATE,
                         Manager_DateUpdated DATE,
                         FOREIGN KEY (Client) REFERENCES Client
)
CREATE TABLE Candidate (
                           Candidate_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                           Candidate_Firstname VARCHAR (100),
                           Candidate_Lastname VARCHAR (100),
                           Assigned_Recruiter INT,
                           Candidate_Email VARCHAR (100),
                           Candidate_Phonenumber VARCHAR (100),
                           Candidate_SSN VARCHAR (100),
                           Candidate_Requested_Pay DECIMAL (5,2),
                           Job_Title_Interested VARCHAR (100),
                           Location_Interested VARCHAR (100),
                           Candidate_Status VARCHAR (100),
                           Candidate_DateCreated DATE,
                           Candidate_DateUpdated DATE,
)
CREATE TABLE Department (
                            Department_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                            Department_Name VARCHAR (100),
                            Department_Status VARCHAR (100),
                            Department_DateCreated DATE,
                            Department_DateUpdated DATE
)
CREATE TABLE Recruiter (
                           Recruiter_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                           Recruiter_Department INT,
                           Recruiter_Firstname VARCHAR (100),
                           Recruiter_Lastname VARCHAR (100),
                           Recruiter_Email VARCHAR (100),
                           Recruiter_Phonenumber VARCHAR (100),
                           Recruiter_Status VARCHAR (100),
                           Recruiter_DateCreated DATE,
                           Recruiter_DateUpdated DATE,
                           FOREIGN KEY (Recruiter_Department) REFERENCES Department
)
CREATE TABLE Job_Category (
                              Job_Category_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                              Job_Category_Name VARCHAR (100),
                              Job_Category_Description VARCHAR (100),
                              Job_Category_Status VARCHAR (100),
                              Job_Category_DateCreated DATE,
                              Job_Category_DateUpdated DATE,
)
CREATE TABLE Job (
                     Job_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                     Job_Title VARCHAR(50),
                     Job_Description VARCHAR(100),
                     Assigned_Manager INT,
                     Client INT,
                     Assigned_Recruiter INT,
                     Department INT,
                     Job_Category INT,
                     Date_Posted DATE,
                     Education_Level VARCHAR (100),
                     Experience_Level VARCHAR (100),
                     Fill_Urgency VARCHAR (100),
                     Job_Location VARCHAR (100),
                     Remote_Onsite VARCHAR (100),
                     Salary_Type VARCHAR (100),
                     Job_Pay DECIMAL (5,2),
                     Job_Type VARCHAR (100),
                     Job_Status VARCHAR (100),
                     Job_DateCreated DATE,
                     Job_DateUpdated DATE,
                     FOREIGN KEY (Assigned_Manager) REFERENCES Manager,
                     FOREIGN KEY (Assigned_Recruiter) REFERENCES Recruiter,
                     FOREIGN KEY (Department) REFERENCES Department,
                     FOREIGN KEY (Job_Category) REFERENCES Job_Category,
)
CREATE TABLE Resume (
                        Resume_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                        Candidate INT,
                        Resume_Body VARCHAR (100),
                        Skills VARCHAR (100),
                        Degree VARCHAR (100),
                        Experience_level VARCHAR (100),
                        Certifications VARCHAR (100),
                        Highest_Education VARCHAR (100),
                        Graduation_Date DATE,
                        Resume_Status VARCHAR (100),
                        Resume_DateCreated DATE,
                        Resume_DateUpdated DATE,
                        FOREIGN KEY (Candidate) REFERENCES Candidate
)
CREATE TABLE Placement (
                           Placement_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                           Client INT,
                           Candidate INT,
                           Job INT,
                           Manager INT,
                           Placement_Date DATE,
                           Placement_Status VARCHAR (100),
                           Placement_DateCreated DATE,
                           Placement_DateUpdated DATE,
                           FOREIGN KEY (Candidate) REFERENCES Candidate,
                           FOREIGN KEY (Client) REFERENCES Client,
                           FOREIGN KEY (Job) REFERENCES Job,
                           FOREIGN KEY (Manager) REFERENCES Manager,
)
CREATE TABLE Assignment (
                            Assignment_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                            Client_ID INT,
                            Placement INT,
                            Manager INT,
                            Candidate INT,
                            Contract_Start_Date DATE,
                            Contract_End_Date DATE,
                            Candi_Rate Decimal (5,2),
                            Bill_Rate Decimal (5,2),
                            Assignment_Status VARCHAR (100),
                            Assignment_DateCreated DATE,
                            Assignment_DateUpdated DATE,
                            FOREIGN KEY (Client_ID) REFERENCES Client,
                            FOREIGN KEY (Placement) REFERENCES Placement,
                            FOREIGN KEY (Candidate) REFERENCES Candidate,
                            FOREIGN KEY (Manager) REFERENCES Manager,
)
CREATE TABLE TimeCard (
                          TimeCard_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                          Candidate INT,
                          Assignment INT,
                          Recruiter INT,
                          Manager INT,
                          Worked_Hours INT,
                          Pay_Begin_Date DATE,
                          Pay_End_Date DATE,
                          Pay_Rate Decimal(5,2),
                          Bill_Rate Decimal(5,2),
                          TimeCard_Status VARCHAR (100),
                          TimeCard_DateCreated DATE,
                          TimeCard_DateUpdated DATE,
                          FOREIGN KEY (Assignment) REFERENCES Assignment,
                          FOREIGN KEY (Candidate) REFERENCES Candidate,
                          FOREIGN KEY (Manager) REFERENCES Manager,
                          FOREIGN KEY (Recruiter) REFERENCES Recruiter,
)
CREATE TABLE Billing (
                         Invoice_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                         Client INT,
                         TimeCard INT,
                         Department INT,
                         Assignment INT,
                         Invoice_Amount Decimal (6,2),
                         Billing_term VARCHAR(35),
                         Amnt_Due_For_Bill_Rate Decimal (6,2),
                         Amnt_Due_For_Candi_Rate Decimal (6,2),
                         Total_Amount_billed Decimal (6,2),
                         Invoice_Status VARCHAR (100),
                         Invoice_DateCreated DATE,
                         Invoice_DateUpdated DATE,
                         FOREIGN KEY (Client) REFERENCES Client,
                         FOREIGN KEY (TimeCard) REFERENCES TimeCard,
                         FOREIGN KEY (Department) REFERENCES Department,
                         FOREIGN KEY (Assignment) REFERENCES Assignment,
)
CREATE TABLE Candidate_Payment (

                                   Payment_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
                                   Department INT,
                                   Recruiter INT,
                                   TimeCard INT,
                                   Check_Amount Decimal (6,2),
                                   Check_Number INT,
                                   Check_Date DATE,
                                   Candidate_Payment_Status VARCHAR (100),
                                   Candidate_Payment_DateCreated DATE,
                                   Candidate_Payment_DateUpdated DATE,
                                   FOREIGN KEY (Department) REFERENCES Department,
                                   FOREIGN KEY (TimeCard) REFERENCES TimeCard,
                                   FOREIGN KEY (Recruiter) REFERENCES Recruiter,

)